const SHOW__ALL = 'SHOW__ALL';
const SHOW__ASCEND__POINT = 'SHOW__ASCEND__POINT';
const SHOW__DESCEND__POINT = 'SHOW__DESCEND__POINT';


export const filters = {
    SHOW__ALL: SHOW__ALL,
    SHOW__ASCEND__POINT: SHOW__ASCEND__POINT,
    SHOW__DESCEND__POINT: SHOW__DESCEND__POINT,
}; 